language: cpp
sudo: required
dist: xenial
compiler:
- g++
- clang
os:
- linux
- osx
before_install:
- if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/dependencies.sh; fi
before_script:
- ./scripts/cmake.sh;
script: cd build/ && make -j16 && ./test/testRunner
branches:
  only:
  - master
  - "/^v(?:\\d+|x)\\.(?:\\d+|x)\\.(?:\\d+|x)(?:-(?:alpha|beta)\\.\\d+)?/"
  - "/^wip-RL-\\d+/"
